In [107]:
import numpy as np
a = np.empty((0,3), int)
print (a)

a = np.append(a, np.array([[1,1,1]]), axis=0)
a = np.append(a, np.array([[3,4,5]]), axis=0)
print(a)

a=[4, 5, 1, 0, 8, 7, 7]
print (a)
print(np.sort(a))
print(np.sort(a)[-1])

[]
[[1 1 1]
 [3 4 5]]
[4, 5, 1, 0, 8, 7, 7]
[0 1 4 5 7 7 8]
8


In [130]:
import numpy as np

f = open('input.txt', 'rt')

#get the dimension of the input
row = f.readline()
row_size = len(row.strip())

#initialize an empty grid
grid = np.empty((0,row_size), dtype='int16')
 
#go back to the beginning of the file
f.seek(0)

#build the grid
for s in f:
    new_row =  np.array([list(s.strip())], dtype='int16')
    grid = np.append(grid, new_row, axis = 0)

#print(grid)

row_size, col_size = grid.shape
print(row_size, col_size)



99 99


In [131]:
def visible(grid, x, y):
    
    x_size, y_size = grid.shape
    up_max = np.sort(grid[0:x, y])[-1]
    down_max = np.sort(grid[x+1:x_size, y])[-1]
    left_max = np.sort(grid[x, 0:y])[-1]
    right_max = np.sort(grid[x, y+1:y_size])[-1]
    val = grid[x,y]
    return val > up_max or val > down_max or val> left_max or val > right_max
  

In [132]:
visible_count = (row_size + col_size) * 2 - 4

print (visible_count)

for i in range(1,row_size-1):
    for j in range(1,col_size-1):
        if visible(grid, i, j):
            visible_count += 1

print (visible_count)


392
1812


In [54]:
# part 2
import numpy as np

f = open('input.txt', 'rt')

#get the dimension of the input
row = f.readline()
row_size = len(row.strip())

#initialize an empty grid
grid = np.empty((0,row_size), dtype='int16')
 
#go back to the beginning of the file
f.seek(0)

#build the grid
for s in f:
    new_row =  np.array([list(s.strip())], dtype='int16')
    grid = np.append(grid, new_row, axis = 0)

#print(grid)

row_size, col_size = grid.shape
print(row_size, col_size)



99 99


In [55]:
def left_dist(grid, x, y):
    x_l, y_l = grid.shape
    my_val = grid[x,y]

    cnt = 0
    if x==0 or x == x_l -1 or y == 0 or y == y_l-1:
        return 0
    else:
        vec = np.flip(grid[x, 0:y])
        #print (vec, vec.size)
        for i in range(vec.size):
            #print(i,vec[i])
            cnt += 1
            if my_val <= vec[i]:
                break
    return cnt

def up_dist(grid, x, y):
    x_l, y_l = grid.shape
    my_val = grid[x,y]

    cnt = 0
    if x==0 or x == x_l -1 or y == 0 or y == y_l-1:
        return 0
    else:
        vec = np.flip(grid[0:x, y])
        #print (vec, vec.size)
        for i in range(vec.size):
            #print(i,vec[i])
            cnt += 1
            if my_val <= vec[i]:
                break
    return cnt

In [56]:
def right_dist(grid, x, y):
    x_l, y_l = grid.shape
    my_val = grid[x,y]

    cnt = 0
    if x==0 or x == x_l -1 or y == 0 or y == y_l-1:
        return 0
    else:
        vec = grid[x, y+1:y_l]
        #print (vec, vec.size)
        for i in range(vec.size):
            #print(i,vec[i])
            cnt += 1
            if my_val <= vec[i]:
                break
    return cnt

def down_dist(grid, x, y):
    x_l, y_l = grid.shape
    my_val = grid[x,y]

    cnt = 0
    if x==0 or x == x_l -1 or y == 0 or y == y_l-1:
        return 0
    else:
        vec = grid[x+1:x_l, y]
        #print (vec, vec.size)
        for i in range(vec.size):
            #print(i,vec[i])
            cnt += 1
            if my_val <= vec[i]:
                break
    return cnt


In [58]:
max = 0
for i in range(row_size):
    for j in range(col_size):
        #print ("pos:", i,j)
        val = left_dist(grid, i, j) * \
              right_dist(grid, i, j) * \
              up_dist(grid, i, j) * \
              down_dist(grid, i, j)
        #print("value:", val)
        if val > max:
            max = val
print(max)


315495
